# Generated by Django 3.1.7 on 2021-04-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('numeroClient', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nomClient', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=50)),
                ('numeroTel', models.CharField(max_length=50)),
                ('numeroWhatsapp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDepot', models.CharField(max_length=50)),
                ('lieu', models.CharField(max_length=50)),
                ('statusDp', models.CharField(choices=[('Active', 'active'), ('No Active', 'no active')], max_length=20)),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('reference', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('capaciter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('typeEnvoi', models.CharField(choices=[('BATEAU', 'Bateau'), ('AVION', 'Avion'), ('CAMION', 'Camion')], max_length=8)),
                ('lieuDepart', models.CharField(max_length=50)),
                ('lieuArriver', models.CharField(max_length=50)),
                ('dateDepart', models.DateField(verbose_name='Date_depart')),
                ('dateArriver', models.DateField(blank=True, null=True, verbose_name='Date_arriver')),
                ('status', models.CharField(choices=[('EN COURS', 'En Cours'), ('LIVRER', 'Livrer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEmployer', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=50)),
                ('numeroTel', models.CharField(max_length=50)),
                ('numeroWhatsapp', models.CharField(max_length=50)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockColi.depot')),
            ],
        ),
        migrations.CreateModel(
            name='Coli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qRCode', models.CharField(max_length=250, unique=True)),
                ('nombrePiece', models.PositiveIntegerField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=8)),
                ('longueur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prixTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Tva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('EN COURS', 'En Cours'), ('LIVRER', 'Livrer')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockColi.client')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockColi.depot')),
                ('envoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockColi.envoi')),
            ],
        ),
    ]
